services:
  postgres:
    restart: always
    image: postgres:17.5-bookworm@sha256:ea51edb26055e9dea6d90e6c82066985a71f3544fa85ff2883f6ca668187aa09
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dsm23-next-payloadcms-postgres-template # THIS MUST MATCH YOUR DB NAME IN .env
      POSTGRES_HOST_AUTH_METHOD: trust

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z@sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data/minio --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - "bucket:/data/minio"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  createbucket:
    image: minio/mc:RELEASE.2025-04-16T18-13-26Z@sha256:aead63c77f9db9107f1696fb08ecb0faeda23729cde94b0f663edf4fe09728e3
    depends_on:
      minio:
        condition: service_healthy
        restart: true
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb myminio/${MINIO_BUCKET};
      mc policy set public myminio/${MINIO_BUCKET};
      mc admin accesskey create myminio/ --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY};
      exit 0;
      "

  mailpit:
    image: axllent/mailpit:v1.25.0@sha256:9ba9ed1bb725518327486c18562e21c55f93b89d1d35454339e8a5c541ce5710
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    environment:
      - MP_MAX_MESSAGES=5000
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      # - MP_UI_AUTH_FILE=/data/htpasswd
      - TZ=Europe/London
    volumes:
      - "mailpit-data:/data"

volumes:
  bucket:
  pgdata:
  mailpit-data:
  node_modules:
